#pragma once

#include "economy/Resource.h"
#include "core/Faction.h"
#include <string>

class Station;

// Mission type. The objective and how it's completed depend on the type.
enum class MissionType
{
    Bounty,    // destroy N pirates
    Mining,    // mine and deliver N units of a resource
    Delivery,  // deliver cargo to another station
};

// A single mission. Generated by the issuing station from a template; once
// accepted it lands in the player's active mission log.
struct Mission
{
    MissionType type = MissionType::Bounty;
    FactionId   faction = FactionId::Independent;  // issuer (the station's faction)
    std::string title;                             // short heading for lists
    std::string description;                       // what needs to be done

    // Stations by stable id (Entity::GetId), not by pointer: a mission must
    // survive the network (the client has no live server objects) and saving (M4f-2).
    int giverStationId = 0;  // issuing station (turn in Bounty/Mining here)
    int destStationId = 0;   // destination station (for Delivery)

    ResourceType resource = ResourceType::Iron;  // what to mine (for Mining)
    int          targetCount = 0;                // how much to mine / kill
    int          progress = 0;                   // current progress (pirate kill counter)

    double rewardMoney = 0.0;
    float  rewardRep = 0.0f;

    // Transient (not saved): whether it can be turned in right now. Over the
    // network the server computes it and puts it in the snapshot (the client field
    // is a mirror, not always accurate locally).
    bool completable = false;
};
