#!/usr/bin/env python3
"""Generate docs/agents/reference.md from what econagent itself says it offers.

    python tools/gen_agent_reference.py <path-to-econagent>          # write the file
    python tools/gen_agent_reference.py <path-to-econagent> --check  # fail if it is stale

The reference is generated rather than written because a hand-kept list of tools is wrong
the first time a tool changes, and a bot author reading wrong documentation fails in a way
that is hard to diagnose. `econagent describe` prints exactly what tools/list, resources/list
and prompts/list answer, with no server and no account; this turns that into Markdown.
CI runs it with --check, so a tool changed without its documentation is a red build (#172).
"""

import json
import os
import subprocess
import sys

OUT = os.path.join(os.path.dirname(__file__), "..", "docs", "agents", "reference.md")


def describe(exe):
    out = subprocess.run([exe, "describe"], capture_output=True, check=True)
    return json.loads(out.stdout.decode("utf-8"))


def lint(d):
    """Refuse a surface a strict MCP client would choke on.

    This is how the first run of this script found that every tool's `properties` was an
    array of [name, schema] pairs rather than an object (#172): the reference could not be
    generated because the schemas were not schemas. Checked here so it cannot come back.
    """
    problems = []
    for tool in d["tools"]:
        schema = tool.get("inputSchema", {})
        where = "tool %s" % tool.get("name", "?")
        if schema.get("type") != "object":
            problems.append("%s: inputSchema.type must be \"object\"" % where)
        props = schema.get("properties", {})
        if not isinstance(props, dict):
            problems.append("%s: inputSchema.properties must be an object, got %s"
                            % (where, type(props).__name__))
            continue
        for req in schema.get("required", []):
            if req not in props:
                problems.append("%s: required argument %r is not among its properties" % (where, req))
        for name, p in props.items():
            if not isinstance(p, dict) or "type" not in p:
                problems.append("%s: argument %r has no type" % (where, name))
            elif not p.get("description"):
                problems.append("%s: argument %r has no description -- a model reads it" % (where, name))
        if not tool.get("description"):
            problems.append("%s: no description -- a model chooses tools by it" % where)
    return problems


def type_of(schema):
    t = schema.get("type", "")
    return " or ".join(t) if isinstance(t, list) else t


def render(d):
    lines = [
        "# econagent reference",
        "",
        "<!-- Generated by tools/gen_agent_reference.py from `econagent describe`. Do not edit by",
        "     hand: change the tool in src/agent/main.cpp and regenerate. CI fails if this file",
        "     disagrees with the binary. -->",
        "",
        "Everything the game's MCP server offers, exactly as it describes itself. The guide that",
        "explains how to use it is [README.md](README.md).",
        "",
        "MCP protocol version: `%s`." % d["protocolVersion"],
        "",
        "## Tools",
        "",
    ]
    for tool in d["tools"]:
        lines += ["### `%s`" % tool["name"], "", tool["description"], ""]
        schema = tool.get("inputSchema", {})
        props = schema.get("properties", {}) or {}
        required = set(schema.get("required", []))
        if not props:
            lines += ["No arguments.", ""]
            continue
        lines += ["| Argument | Type | Required | Meaning |", "|---|---|---|---|"]
        for name in props:
            p = props[name]
            lines.append("| `%s` | %s | %s | %s |" % (
                name, type_of(p), "yes" if name in required else "", p.get("description", "")))
        lines.append("")

    lines += ["## Resources", "", "| URI | Name | What |", "|---|---|---|"]
    for r in d["resources"]:
        lines.append("| `%s` | %s | %s |" % (r["uri"], r["name"], r["description"]))
    lines.append("")

    lines += ["## Prompts", "",
              "Ready-made plans a client can offer its user. Each is sent to the model as written.",
              ""]
    for p in d["prompts"]:
        lines += ["### `%s`" % p["name"], "", "*%s*" % p["description"], "", "> " + p["text"], ""]

    return "\n".join(lines).rstrip("\n") + "\n"


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    d = describe(sys.argv[1])
    problems = lint(d)
    if problems:
        print("econagent describes itself in a way an MCP client would not accept:")
        for p in problems:
            print("  -", p)
        return 1
    text = render(d)
    path = os.path.normpath(OUT)

    if "--check" in sys.argv[2:]:
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        if current != text:
            print("docs/agents/reference.md is out of date with what econagent offers.")
            print("Regenerate it:  python tools/gen_agent_reference.py <path-to-econagent>")
            return 1
        print("docs/agents/reference.md matches econagent.")
        return 0

    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote", path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
